apiVersion: v1
kind: Service
metadata:
  name: multiportservice
spec:
  selector:
    app: surya
  ports:
    - name: proxy
      port: 8082
      targetPort: 80
    - name: application
      port: 8081
      targetPort: 8080
